node --max-old-space-size=20000000 artists/artgraph_creation.js
mv labels.json ./artists
mv links.bin ./artists
mv data ./artists
node --max-old-space-size=20000000 designers/desgraph_creation.js
mv labels.json ./designers
mv links.bin ./designers
mv data ./designers
node --max-old-space-size=20000000 families/famgraph_creation.js
mv labels.json ./families
mv links.bin ./families
mv data ./families
node --max-old-space-size=20000000 genres/gengraph_creation.js
mv labels.json ./genres
mv links.bin ./genres
mv data ./genres
node --max-old-space-size=20000000 mechanics/mechgraph_creation.js
mv labels.json ./mechanics
mv links.bin ./mechanics
mv data ./mechanics
node --max-old-space-size=20000000 publishers/pubgraph_creation.js
mv labels.json ./publishers
mv links.bin ./publishers
mv data ./publishers
